elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.1.1
  ports:
    - "9200:9200"
  container_name: elasticsearch
  hostname: elasticsearch
  environment:
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"
    - "xpack.security.enabled=false"
logstash:
  image: docker.elastic.co/logstash/logstash:5.1.1
  ports:
    - "5044:5044"
    - "9300:9300"
    - "9600:9600"
  container_name: logstash
  links: 
    - elasticsearch
  volumes:
    - ./pipeline/:/usr/share/logstash/pipeline/:ro
kibana:
  image: docker.elastic.co/kibana/kibana:5.1.1
  ports:
    - "5601:5601"
  container_name: kibana
  links: 
    - elasticsearch
